### PR TITLE
Get rid of bash again

### PR DESCRIPTION
**Pull request by jsarenik**
Be more POSIX. http://pubs.opengroup.org/onlinepubs/9699919799/

### CODE REVIEW

**Comment by jsarenik** [comment]
@urg What do you think about this one?

**Comment by jsarenik** [comment]
By the way, I am running on `mksh` but it has many bash-like extensions to POSIX so that's why I did not notice the `let` directive being `bash`-related.

**Comment by urg** [comment]
@jsarenik - sorry for the delay - I need to whitelist github emails

With this branch, running what we do in prod `./despf.sh spf-orig.peerj.com | ./mkblocks.sh peerj.com _spf`, I get `./mkblocks.sh: 34: ./mkblocks.sh: Bad substitution`.  Will try to investigate further soon.

**Comment by jsarenik** [comment]
@urg Thanks for feed-back! Not merging yet, invistigating. What shell type and version do you use?

**Comment by urg** [comment]
`GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)`

My guess is that sh doesn't support string find/replace (e.g. `${footer/X/1}`) and would need to use sed for that?

**Comment by jsarenik** [comment]
Right.

**Comment by jsarenik** [comment]
As for tests, see #13

**Comment by jsarenik** [comment]
Rebased to latest master.

**Comment by jsarenik** [comment]
@urg Let me know if you are OK with it and feel free to merge if yes.

**Comment by urg** [comment]
@jsarenik - I think its fine.  I'm just having a problem with the dns on my local computer and getting a `dig: couldn't get address for ';;': not found` error, which I was trying to track down before responding.  Its occurring on the other branch as well, so probably fine ;)

**Comment by jsarenik** [comment]
@urg Which command gives you the error? Can you run it possibly with `sh -x`?

**Comment by urg** [comment]
It seems as though my new office is restricting dns lookups.  Works fine at home.

**Comment by jsarenik** [comment]
@urg Does https://github.com/jsarenik/spf-tools/pull/15 solve the issue at work?

**Comment by jsarenik** [comment]
See #17

**Pull request closed without merging**
