### PR TITLE
policy now is a cmd line parameter. Fix #89

### LINKED ISSUE #89: Make default policy a cmd line setting in mkblocks.sh
mkblocks has a hardcoded policy="~all" . It would be nice to be configurable

### PR DESCRIPTION
**Pull request by jcbf**

### CODE REVIEW

**Comment by jsarenik** [comment]
Looks good. Though it's just positional parameter (like the others are). I would like to add getopt(s) later.

Thanks!

**Comment by jcbf** [comment]
Thought about using getopt but it would add an external dependency and would require more changes :p

**Comment by jsarenik** [comment]
Have a look at #93

**Comment by jsarenik** [comment]
#92

**Pull request merged**
