### PR TITLE
Add AWS route53 DNS updating script

### PR DESCRIPTION
**Pull request by AlexCline**
This script will use the AWS CLI to update spf DNS records in Route53.

The AWS CLI requires IAM credentials which can be configured using
environment variables (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY),
or using the AWS configuration file (~/.aws/credentials).

The script is used inline with `mkblocks.sh` and requires a Hosted Zone ID
as the first parameter.

```
./despf.sh | ./simplify.sh | ./mkblocks.sh | ./route53.sh ABCXYZEXAMPLE
```

An optional `-t` parameter can be specified to change the TTL.

### CODE REVIEW

**Comment by jcbf** [comment]
Looks good. I was thinking of doing a similar one :p .

Anyway , I see a possible enhancement . Allow  -p option to pass allow the usage of awscli profile

I have a couple of doubts. 
 * Will that work for non existing zone ? 
 * Is it worth to check diferences before unconditional update ?


In any cases this can be added after and is good as is.

+1 for me.

**Comment by jsarenik** [comment]
Please rebase to current master and force-push.

**Comment by AlexCline** [comment]
@jcbf, thanks for the feedback.

- We don't currently use awscli profiles in our environment, so this is something that would be difficult for me to test.
- The awscli will return an error if the hosted_zone_id specified does not exist.
- In my environment, we're using `compare.sh` which is behaving as expected with route53.

@jsarenik I've merged in the changes from this repo's master and repushed. Tests are running.

**Comment by jsarenik** [comment]
Merging. Sorry for delay.

**Pull request merged**
