### PR TITLE
Implement address checking for both v4 and v6

### PR DESCRIPTION
**Pull request by jsarenik**
Following functions were added:
  - checkval4
  - checkval6
  - canon6
  - shorten6 (unused)

Includes unit tests

Fixes GitHub issue #48

### CODE REVIEW

**Comment by jcbf** [comment]
Looks good except for the unused  shorten6 that doesn't handle properly 2001:0:0:2344:0:0:0:23

**Comment by jsarenik** [comment]
@jcbf `shorten6` deleted. Just out of curiosity, why would `2001::2344:0:0:0:23` not be proper? Does RFC require to shorten the longest set of zeroes in the row?

**Comment by jcbf** [comment]
That was just nitpicking. Is still valid but for purposes of optimization it's expected that the bigger 0:0: block is the shortened.
Again, just nitpicking since it was an unused function.

**Comment by jsarenik** [comment]
So I'm merging this in. Thanks for feed-back!

**Pull request merged**
