### PR TITLE
Jasan/119 paste

### PR DESCRIPTION
**Pull request by jsarenik**
@jcbf please have a look at this instead.

### CODE REVIEW

**Comment by jsarenik** [comment]
Oops, not there yet.

**Comment by jsarenik** [comment]
@jcbf please have a look now.

**Comment by jcbf** [comment]
I would prefer the `sed -e 's/" "//g` over the `paste .. tr` because is simple and don't have to rely on more tools. For consistency checks you should also add them to the check on all scripts

> grep "for cmd" -r *
> cloudflare.sh:for cmd in jq awk sed grep
> despf.sh:for cmd in host awk grep sed cut
> misc/ci-runtest.sh:for cmd in host awk grep sed cut
> mkblocks.sh:for cmd in awk grep sed cut
> mkzoneent.sh:for cmd in awk grep sed cut
> simplify.sh:for cmd in awk grep sed cut

**Comment by jcbf** [comment]
It's probably better to push different fixes into different  pull's.
And now I understand why is falling...

**Pull request closed without merging**
