### PR TITLE
Better handle for records with qualifier

### PR DESCRIPTION
**Pull request by jcbf**
* Fix for #135.
* Remove sorted output.
* Mechanism `a` and `mx` now look for a modifier.
* `printip` may receive the qualifier upfront
* Add more unit tests for `printip`

### CODE REVIEW

**Comment by jsarenik** [comment]
If the output is not sorted, the tests will most probably fail.

**Comment by jcbf** [comment]
Now I remember why I left the "sort" patch initially out :p 
I'm on it.

Can you create some new records with some qualifiers ?

**Comment by jsarenik** [comment]
@jcbf Here is one:

```
$ host -t txt both-spf-q.jasan.tk                                              
both-spf-q.jasan.tk descriptive text "v=spf1 +a:both.jasan.tk -a:139.1.3.9 ?a:127.1.2.7 ~all"
```

I can add any other but please help me with ideas.

**Comment by jcbf** [comment]
hmm ... -a:139.1.3.9 ?a:127.1.2.7 is not valid :p 

you can add something like

`-ip4:1.2.3.4 +ip4:1.2.30/24` and   `-mx:/30 +mx:24`

**Comment by jsarenik** [comment]
@jcbf Thank you for feed-back!

```
$ host -t txt both-spf-q.jasan.tk
both-spf-q.jasan.tk descriptive text "v=spf1 +a:both.jasan.tk -ip4:139.1.3.9 ?ip4:127.1.2.7 ~all"
$ host -t txt jcbf.jasan.tk
jcbf.jasan.tk descriptive text "v=spf1 -ip4:1.2.3.4 +ip4:1.2.30/24 and -mx:/30 +mx:24 ~all"
```

**Comment by jsarenik** [comment]
@jcbf - one more thing. If `sort` is not being done anymore, the documentation should be updated accordingly.

```
$ git fetch --all
$ git checkout jcbf/handle_qualifiers
Switched to branch 'jcbf/handle_qualifiers'
Your branch is up-to-date with 'origin/jcbf/handle_qualifiers'.
$ git grep sort
README.md:Decompose SPF records of a DOMAIN, sort and unique them.
README.md:`sort(1)`ed and `uniq(1)`ed to stdout, one per line.
cloudflare.sh:  tr -d "\"" | sort > $idsfile
despf.sh:       Decompose SPF records of a DOMAIN, sort and unique them.
include/despf.inc.sh:  # Make sort(1) behave
tests/despf_help/out:Decompose SPF records of a DOMAIN, sort and unique them.
tests/test-unit.sh:  test -s $tmp-out && { sort $tmp-real | diff -u $tmp-out -; }
tests/test-unit.sh:testexpect 0 "get_ns jasan.tk | sort" <<EOF
```

**Comment by jcbf** [comment]
I was considering add sort as a cmd line option on a different patch.

**Comment by jcbf** [comment]
@jsarenik 
the host `jcbf.jasan.tk` has some typos:
`+ip4:1.2.30/24` you missed a dot
` -mx:/30` is invalid. Should  be  `-mx/30`
 `+mx:24` is not invalid but doesn't resolve . Should be  `+mx/24`


for copy/paste purpose here the final record:

`"v=spf1 -ip4:1.2.3.4 +ip4:1.2.3.0/24 -mx/30 +mx/24 ~all"`

I'll add test for this record and do a final push.

**Comment by jsarenik** [comment]
@jcbf thanks again for correction. Fixed now. May need some cache time-out.

**Comment by jsarenik** [comment]
@jcbf Yes, a new cmdline option without breaking the previous behavior is the best thing to do! Thank you!

**Comment by jcbf** [comment]
This is conditional sorting. If no qualifier if found ( `+` when found is removed ) then the output is sorted as before. If any other is found, leave as is.
I can add command line option for  `always sort`, `never sort` or `auto sorting` but sent is as a different PR.

Does this make sense ?

**Comment by jsarenik** [comment]
@jcbf yes, it makes a lot of sense. Excellent idea! Reviewing now...

**Pull request merged**
