### PR TITLE
Phavekes + little fixes

### PR DESCRIPTION
**Pull request by jsarenik**

### CODE REVIEW

**Comment by jsarenik** [comment]
@jcbf I had to remove `bashcov` (and for the sake of it all coverage-related lines in `.travis.yml`). If you have an idea how to fix it properly (while leaving the coverage functionality in place) I will be happy for your input.

**Comment by jsarenik** [comment]
@phavekes please have a look and let me know what you think (do not mind the patch to `.travis.yml` as it is not related).

**Comment by jcbf** [comment]
Created #149 to fix bashcov dependency.

**Comment by jsarenik** [comment]
Closing in favour of original #147 or possibly something like `jasan/phavekes-fixes`

**Pull request closed without merging**
