### PR TITLE
Add suffix option

### PR DESCRIPTION
**Pull request by Vhex**
Add option to postfix the DNS name in addition to the existing prefix.  This allows us to do things like:
_1.spf.domain.com

### CODE REVIEW

**Comment by Vhex** [comment]
Valid point on the suffix comment, I'll make that change as well.  "Pre" and "Post" made so much sense last week. ;-)

Do you want it in a clean pull request?

**Comment by jcbf** [comment]
You may commit to that branch. Please also  include the test file changes that I suggested in the review.

**Comment by Vhex** [comment]
Yep, will do on the tests as well -- I just meant I would change it to suffix in addition to doing the tests.

**Comment by jsarenik** [comment]
Please rebase to current master and force-push.

**Comment by Vhex** [comment]
Rebased from the current master and squashed commits.

**Comment by jsarenik** [comment]
@Vhex oops, I am sorry for merging PRs in random order. Now this one does not merge cleanly. Please have a look what can be causing that. Thanks!

**Comment by Vhex** [comment]
I see.  I used S for suffix and someone else used S for start.  I'll update to X again.

**Comment by Vhex** [comment]
I updated my changes against the current master.  Should be good now.

**Comment by jsarenik** [comment]
@Vhex thank you!

**Pull request merged**
